name: PHPCS check

on: [pull_request, push]

jobs:
  phpcs:
      name: PHPCS
      runs-on: ubuntu-latest
      steps:
        - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          tools: php-cs-fixer